### ISSUE TITLE
Maixduino Schematic

### ISSUE THREAD

**Issue by pollock94** [sipeed/Sipeed_HardWare#1]
Hi,

I was wondering whether the schematic of Sipeed Maixduino is available? I want to customize the design for my application. Thank you

**Comment by QinYUN575** [comment]
Of course you can click this link to download the schematic of MaixDuino
[MaixDuino schematic](https://dl.sipeed.com/MAIX/HDK/Sipeed-Maixduino/Maixduino_2832)
